import sys
from time import sleep

inputFile = sys.argv[0]
inputFile = inputFile.split(".")[0]

with open(inputFile + ".sh", "w") as f:
	f.write('echo "hello world"')
print("compiling...")
sleep(4.0)
print("ahhhhh something probably went wrong we suck at coding")
sleep(2.0)
print("lol we fixed it")
sleep(2.0)
print("sike jk")
sleep(2.0)
print("what are we doing rn")
sleep(2.0)
print("almost there")
sleep(2.0)
print("wait")
sleep(2.0)
print("??")
sleep(2.0)
print("somethings wrong!!")
sleep(2.0)
print("...")
sleep(2.0)
print("???????")
sleep(2.0)
print("you might want to figure this out")
sleep(3.0)
print("...")
sleep(3.0)
print("...")
sleep(3.0)
print("yeet")
sleep(1.0)
print("h")
sleep(1.0)
print("h")
sleep(1.0)
print("h")
sleep(2.0)
print("e")
sleep(1.0)
print("l")
sleep(0.5)
print("l")
sleep(0.5)
print("o")
sleep(0.5)
print(" ")
sleep(1.0)
print("w")
sleep(2.0)
print("...")
sleep(2.0)
print("o")
sleep(1.0)
print("r")
sleep(1.0)
print("l")
sleep(1.0)
print("d")
sleep(1.0)
print(".....!")
sleep(2.0)
